
package:
  name: dunovo
  version: 0.6.2

source:
  fn: v0.6.2.tar.gz
  url: https://github.com/galaxyproject/dunovo/archive/v0.6.2.tar.gz
  sha256: 04cb2646b5b451add8bf39d1d458e178b16318fe2a9f4958a7fe5c00a6d9a354

build:
  number: 0

requirements:
  skip: True  # [py3k or osx]
  build:
    - make
    - gcc

  run:
    - libgcc
    - python >=2.6
    - argparse  # [py26]
    - mafft 7.221
    - samtools 0.1.18
    - bowtie2 2.2.4
    - networkx
    - paste
    - gawk

test:
  commands:
    - 'correct.py -h > /dev/null'
    - 'align_families.py -h > /dev/null'
    - 'dunovo.py -h > /dev/null'

about:
  home: https://github.com/galaxyproject/dunovo
  license: BSD
  license_file: LICENSE.txt
  summary: "Du Novo: A pipeline for processing duplex sequencing data."
